name: Create Branches2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  create-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history for branch creation

      - name: Set up Git user
        run: |
          git config --global user.name "kumarGitHub123"
          git config --global user.email "kumarnv.math@gmail.com"

      - name: Create multiple branches
        run: |
          BASE_BRANCH="main"
          BRANCH_PREFIX="feature-branch"
          git fetch origin

          git checkout $BASE_BRANCH
          git pull origin $BASE_BRANCH

          for i in $(seq 1 5); do
              BRANCH_NAME="${BRANCH_PREFIX}-${i}"
              git checkout -b $BRANCH_NAME
              git push origin $BRANCH_NAME
              echo "✅ Created and pushed branch: $BRANCH_NAME"
          done

      - name: Switch back to base branch
        run: git checkout main
